languageCode = "en"
languageName = "English"
weight = 1
title = "Ctrl+Alt+Dark"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
description = "My awesome website"
dateFormat = "2 January 2006"
logo = "favicon.png"
secondaryLogo = "favicon.ico"

[params.author]
  name = "Darkrym"
  email = "james.northey@proton.me"
  image = "img/avatar.png"
  headline = "Ctrl+Alt+Dark - A Cyber Blog"
  bio = "SOC Analyst @HuntressLabs | Malware Junkie"
  links = [
    { email = "mailto:james.northey@proton.me" },
    { github = "https://github.com/Darkrym" },
    { linkedin = "https://www.linkedin.com/in/j-northey/" },
    { twitter = "https://x.com/darkrym11" },
  ]
